### ISSUE TITLE
Broken URL for use propType example

### ISSUE THREAD

**Issue by divyenduz** [Khan/style-guides#41]
Hey, I noticed a broken link at line 171 of the document in section.

Document: https://github.com/Khan/style-guides/blob/master/style/react.md

Broken URL :
https://github.com/Khan/webapp/blob/32aa862769d4e93c477dc0ee0388816056252c4a/javascript/search-package/search-results-list.jsx#L14

**Comment by spicyj** [comment]
See #32.
